version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    container_name: task-manager-backend
    ports:
      - '3500:3500'
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: task-manager
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task-manager
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/task-manager.sql:/docker-entrypoint-initdb.d/task-manager.sql:ro
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    container_name: task-manager-frontend
    ports:
      - '3000:80'
    environment:
      - VITE_APP_BASE_URL=http://localhost:3500
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
